spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: post123
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/master.xml
